# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_day', models.DateField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=20, max_digits=30)),
                ('thold', models.DecimalField(decimal_places=20, max_digits=30)),
                ('hashes', models.IntegerField()),
                ('difficulty', models.DecimalField(decimal_places=20, max_digits=30)),
                ('exchange_xmr_cny', models.DecimalField(decimal_places=20, max_digits=30)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
    ]
