# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmr_cny', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='balancehistory',
            name='exchange_xmr_cny',
        ),
    ]
