# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170912_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangehistory',
            options={'ordering': ['-log_time']},
        ),
        migrations.AddField(
            model_name='exchangehistory',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
