# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170912_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(max_length=100)),
                ('expired', models.IntegerField(max_length=20)),
                ('hashes', models.IntegerField(max_length=20)),
                ('hashrate', models.DecimalField(decimal_places=20, max_digits=30)),
                ('last_share', models.DateTimeField()),
            ],
            options={
                'ordering': ['-log_time'],
            },
        ),
    ]
